from . import consts, convert
from ._riichienv import (
    ACTION_SPACE_3P_V0,
    ACTION_SPACE_3P_V1,
    ACTION_SPACE_4P_V0,
    ACTION_SPACE_4P_V1,
    DREV_CHANNELS,
    DREV_V2_CHANNEL_NAMES,
    DREV_V2_CHANNELS,
    DREV_V2_OPPONENT_SLOT_ORDER,
    DREV_V2_SCHEMA_ID,
    DREV_V2_YAKU_EVIDENCE_NAMES,
    OBS_EXTENDED_CHANNELS,
    OBS_EXTENDED_CHANNELS_3P,
    OBS_TOTAL_CHANNELS,
    OBS_TOTAL_CHANNELS_3P,
    SP_CHANNELS,
    TILE_TYPES,
    TILE_TYPES_3P,
    BatchGameEngine,
    EventJournal,
    GameEngine,
    GameRule,
    Kyoku,
    Meld,
    MeldType,
    MjaiReplay,
    MjSoulReplay,
    Observation,
    Observation3P,
    Phase,
    RiichiEnv,
    Score,
    Wind,
    WinResult,
    WinResultContext,
    Yaku,
    calculate_score,
    calculate_shanten,
    calculate_shanten_3p,
    check_riichi_candidates,
    encode_base_batch,
    encode_base_batch_3p,
    encode_drev_batch,
    encode_drev_batch_3p,
    encode_drev_v2_batch,
    encode_drev_v2_batch_3p,
    encode_extended_batch,
    encode_extended_batch_3p,
    encode_extended_with_sp_batch,
    encode_extended_with_sp_batch_3p,
    encode_extended_with_sp_drev_v2_batch,
    encode_extended_with_sp_drev_v2_batch_3p,
    encode_sp_batch,
    encode_sp_batch_3p,
    get_all_yaku,
    get_yaku_by_id,
    parse_hand,
    parse_tile,
)
from .action import Action, Action3P, ActionType
from .game_mode import GameType
from .hand import Conditions, HandEvaluator, HandEvaluator3P

EAST = Wind.East
SOUTH = Wind.South
WEST = Wind.West
NORTH = Wind.North


def _get_viewer(self):
    # Lazy import to avoid circular dependency: visualizer imports from riichienv
    from riichienv.visualizer import GameViewer  # noqa: PLC0415

    return GameViewer(self.mjai_log)


RiichiEnv.get_viewer = _get_viewer  # type: ignore[attr-defined]


__all__ = [
    "ACTION_SPACE_3P_V0",
    "ACTION_SPACE_3P_V1",
    "ACTION_SPACE_4P_V0",
    "ACTION_SPACE_4P_V1",
    "DREV_CHANNELS",
    "DREV_V2_CHANNELS",
    "DREV_V2_CHANNEL_NAMES",
    "DREV_V2_OPPONENT_SLOT_ORDER",
    "DREV_V2_SCHEMA_ID",
    "DREV_V2_YAKU_EVIDENCE_NAMES",
    "OBS_EXTENDED_CHANNELS",
    "OBS_EXTENDED_CHANNELS_3P",
    "OBS_TOTAL_CHANNELS",
    "OBS_TOTAL_CHANNELS_3P",
    "SP_CHANNELS",
    "TILE_TYPES",
    "TILE_TYPES_3P",
    "consts",
    "convert",
    "EventJournal",
    "GameEngine",
    "BatchGameEngine",
    "WinResultContext",
    "Kyoku",
    "Meld",
    "MeldType",
    "Observation",
    "Observation3P",
    "MjSoulReplay",
    "MjaiReplay",
    "Score",
    "Wind",
    "calculate_score",
    "calculate_shanten",
    "calculate_shanten_3p",
    "check_riichi_candidates",
    "encode_base_batch",
    "encode_base_batch_3p",
    "encode_drev_batch",
    "encode_drev_batch_3p",
    "encode_drev_v2_batch",
    "encode_drev_v2_batch_3p",
    "encode_extended_batch",
    "encode_extended_batch_3p",
    "encode_extended_with_sp_batch",
    "encode_extended_with_sp_batch_3p",
    "encode_extended_with_sp_drev_v2_batch",
    "encode_extended_with_sp_drev_v2_batch_3p",
    "encode_sp_batch",
    "encode_sp_batch_3p",
    "parse_hand",
    "parse_tile",
    "Action",
    "Action3P",
    "ActionType",
    "RiichiEnv",
    "GameRule",
    "Phase",
    "GameType",
    "WinResult",
    "HandEvaluator",
    "HandEvaluator3P",
    "Conditions",
    "EAST",
    "SOUTH",
    "WEST",
    "NORTH",
    "Yaku",
    "get_yaku_by_id",
    "get_all_yaku",
]
