const fs = require('fs');
const path = require('path');

const TILES_DIR = path.join(__dirname, '..', 'riichienv-mahjong-tiles-regular');
const OUTPUT_FILE = path.join(__dirname, '..', 'src', 'tiles.ts');

if (!fs.existsSync(TILES_DIR)) {
    console.error(`Error: Tiles directory not found at ${TILES_DIR}`);
    console.error("Please ensure the 'riichienv-mahjong-tiles-regular' directory exists in the project root.");
    process.exit(1);
}

const mapFileNameToId = (filename) => {
    // Map FluffyStuff filenames to our IDs (or MJAI style strings)
    // MJAI: 1m, 2m... 5mr (red 5), 1p... 1s... 1z..7z
    // FluffyStuff: Man1.svg... Man5-Dora.svg... Pin1... Sou1... Ton, Nan, Shaa, Pei, Haku, Hatsu, Chun

    const name = path.basename(filename, '.svg');

    if (name === 'Back') return 'back';
    if (name === 'Blank') return 'blank';
    if (name === 'Front') return 'front';

    const suits = { 'Man': 'm', 'Pin': 'p', 'Sou': 's' };

    for (const [prefix, suffix] of Object.entries(suits)) {
        if (name.startsWith(prefix)) {
            const rest = name.slice(prefix.length); // "1", "5", "5-Dora"
            if (rest.includes('-Dora')) {
                return '5' + suffix + 'r';
            }
            return rest + suffix;
        }
    }

    const honors = {
        'Ton': 'E', 'Nan': 'S', 'Shaa': 'W', 'Pei': 'N',
        'Haku': 'P', 'Hatsu': 'F', 'Chun': 'C'
    };

    if (honors[name]) {
        return honors[name];
    }

    return null;
};

const main = () => {
    const files = fs.readdirSync(TILES_DIR).filter(f => f.endsWith('.svg'));
    const tileMap = {};

    files.forEach(file => {
        const id = mapFileNameToId(file);
        if (id) {
            let content = fs.readFileSync(path.join(TILES_DIR, file), 'utf8');
            // Strip width/height attributes to allow CSS scaling
            content = content.replace(/\s(width|height)="[^"]*"/g, '');
            // Ensure viewBox is preserved (assumed present)
            tileMap[id] = content;
        }
    });

    // Alias 0m/0p/0s to red tiles if they exist
    if (tileMap['5mr']) tileMap['0m'] = tileMap['5mr'];
    if (tileMap['5pr']) tileMap['0p'] = tileMap['5pr'];
    if (tileMap['5sr']) tileMap['0s'] = tileMap['5sr'];

    const outputContent = `// Auto-generated by scripts/gen_tiles.js
export const TILES: Record<string, string> = ${JSON.stringify(tileMap, null, 2)};
`;

    fs.writeFileSync(OUTPUT_FILE, outputContent);
    console.log(`Generated ${OUTPUT_FILE} with ${Object.keys(tileMap).length} tiles.`);
};

main();
